language: python
matrix:
  include:
    - python: 3.9.1
      env: TOXENV=py39
install:
  - sudo apt-get install man-db manpages-posix manpages-dev manpages-posix-dev
  - pip install tox .
script:
  - tox
